### ISSUE TITLE
[deleted]

### ISSUE THREAD

**Issue by resdevd** [rendmp/Britecore-Software-Engineer-Implementation#1]
it's a potential scam, they never hire anyone and makes you finish an entire project. Just search for britecore in github, you can see hundreds of projects submitted over 3 years.

**Comment by rendmp** [comment]
What is your proof of this statement?
There's only 256 projects and that's dont mean that they are not hire or have to hire everyone.

**Comment by resdevd** [comment]
The company size is less than 10 ppl, they've been advertising same position for 3 years. I'm just trying to help you out, i'm not a lawyer to argue my case and provide proofs. 
It's up to you.
